SELECT PEDIDO.TIPO_PAGAMENTO , concat(CLIENTE.NOME," ",CLIENTE.SOBRENOME) AS NOME_COMPLETO FROM PEDIDO
JOIN CLIENTE ON PEDIDO.ID_CLIENTE = CLIENTE.ID_CLIENTE;

SELECT  COUNT(TIPO_PAGAMENTO) AS CONTADOR, TIPO_PAGAMENTO FROM PEDIDO group by TIPO_PAGAMENTO HAVING CONTADOR > 1 ;